name: webviewx_web
description: A feature-rich webview using iframe for web
repository: https://github.com/cqray/webviewx_web
version: 0.3.5

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6 # https://pub-web.flutter-io.cn/packages/http
  pointer_interceptor: ^0.9.3+4 # https://pub-web.flutter-io.cn/packages/pointer_interceptor
  uuid: ^3.0.7 # https://pub-web.flutter-io.cn/packages/uuid
  webview_flutter_platform_interface: ^2.5.0 #https://pub-web.flutter-io.cn/packages/webview_flutter_platform_interface
  webview_flutter_wkwebview: ^3.7.3 # https://pub-web.flutter-io.cn/packages/webview_flutter_wkwebview

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
